# Generated by Django 6.0.7 on 2026-08-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک / گواهینامه')),
                ('issuer', models.CharField(max_length=200, verbose_name='صادرکننده')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه گواهینامه')),
                ('credential_url', models.URLField(blank=True, null=True, verbose_name='لینک اعتبار سنجی گواهینامه')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=150, verbose_name='نام فرستنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل فرستنده')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=150, verbose_name='نام شرکت / سازمان')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل کار (شهر/کشور)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع به کار')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام همکاری')),
                ('is_current', models.BooleanField(default=False, verbose_name='همچنان در این شغل مشغولم')),
                ('description', models.TextField(verbose_name='توضیحات و دستاوردها')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('technologies', models.CharField(help_text='تکنولوژی\u200cهای استفاده شده (مثلا: Django, React, PostgreSQL)', max_length=255, verbose_name='تکنولوژی\u200cها')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر کاور پروژه')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='لینک دمو (مشاهده آنلاین)')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='لینک سورس\u200cکد (گیت\u200cهاب)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پروژه ویژه؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغلی / تخصص')),
                ('bio', models.TextField(verbose_name='درباره من / بیوگرافی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='تصویر آواتار')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='فایل رزومه (PDF)')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('github', models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='لینک تلگرام')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='کلمات کلیدی را با کاما (,) از هم جدا کنید', max_length=255, null=True, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'پروفایل سایت',
                'verbose_name_plural': 'پروفایل\u200cهای سایت',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده؟')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مهارت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مهارت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'مبتدی'), (2, 'متوسط'), (3, 'پیشرفته'), (4, 'متخصص (Expert)')], default=2, verbose_name='سطح تسلط')),
                ('icon_class', models.CharField(blank=True, help_text='کلاس فونت\u200cآیکون یا آیکون کامپوننت فرانت\u200cاند (مثلا: fab fa-python یا devicon-django-plain)', max_length=100, null=True, verbose_name='کلاس آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory', verbose_name='دسته\u200cبندی مرتبط')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['-level', 'name'],
            },
        ),
    ]
