# Generated by Django 6.0.7 on 2026-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='siteprofile',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project completion date (leave blank if ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Check if the project is finished'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_open_source',
            field=models.BooleanField(default=False, help_text='Check if this is an open-source project'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='resume_en',
            field=models.FileField(blank=True, help_text='English Resume', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated technologies (e.g. Django, Vue.js)', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Persian/Main Resume', null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
